/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background:                "#FDFAF4",
        surface:                   "#F8F0E0",
        "primary-container":       "#f4e3bb",
        "on-primary-container":    "#716545",
        primary:                   "#695d3e",
        "on-primary":              "#ffffff",
        "primary-fixed":           "#f2e1b9",
        "primary-fixed-dim":       "#d5c59f",
        "inverse-primary":         "#d5c59f",
        secondary:                 "#735b28",
        "on-secondary":            "#ffffff",
        "secondary-container":     "#fddb9c",
        "on-secondary-container":  "#785f2c",
        "secondary-fixed":         "#ffdea2",
        "secondary-fixed-dim":     "#e2c286",
        tertiary:                  "#835425",
        "on-tertiary":             "#ffffff",
        "tertiary-container":      "#ffdec4",
        "on-tertiary-container":   "#8b5a2b",
        "tertiary-fixed":          "#ffdcc1",
        "tertiary-fixed-dim":      "#f9ba82",
        "on-tertiary-fixed":       "#2e1500",
        "on-tertiary-fixed-variant":"#683d0f",
        "on-background":           "#1d1b19",
        "surface-dim":             "#ded9d4",
        "surface-bright":          "#fef8f3",
        "surface-container-lowest":"#ffffff",
        "surface-container-low":   "#f8f3ee",
        "surface-container":       "#f2ede8",
        "surface-container-high":  "#ede7e2",
        "surface-container-highest":"#e7e2dd",
        "on-surface":              "#1d1b19",
        "on-surface-variant":      "#4b463c",
        "inverse-surface":         "#32302d",
        "inverse-on-surface":      "#f5f0eb",
        outline:                   "#7c766b",
        "outline-variant":         "#cdc6b8",
        "surface-tint":            "#695d3e",
        "surface-variant":         "#e7e2dd",
        "text-primary":            "#2F1B0C",
        "text-body":               "#4A4A4A",
        "border-subtle":           "rgba(194, 164, 106, 0.25)",
        "on-secondary-fixed-variant": "#594313",
        "on-primary-fixed":        "#231b03",
        "on-primary-fixed-variant":"#504628",
        "on-secondary-fixed":      "#261900",
        error:                     "#ba1a1a",
        "on-error":                "#ffffff",
        "error-container":         "#ffdad6",
        "on-error-container":      "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile":  "16px",
        gutter:           "24px",
        "container-max":  "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        heading: ['"XiangQiao"', '"BlueCustard"', '"Plus Jakarta Sans"', "sans-serif"],
        body:    ['"XiangQiao"', '"BlueCustard"', '"Work Sans"', "PingFang SC", "sans-serif"],
      },
      fontSize: {
        "display-lg":  ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md":    ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":    ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
